AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'vendor/bundle/**/*'
  SuggestExtensions: false
  DisabledByDefault: false
  DisplayWarning: false

Lint:
  Enabled: true
  Warning: false
