inherit_from:
  - node_modules/@prettier/plugin-ruby/rubocop.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  ForceExclusion: true
  Exclude:
    - 'node_modules/**/*'

Style/QuotedSymbols:
  Enabled: false
