name: "Rubocop"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '16 5 * * 0'

permissions:
  contents: read
  security-events: write

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf
      with:
        ruby-version: 3.2.1

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Prettier and plugin-ruby
      run: |
        npm install --save-dev prettier@3.4.2 @prettier/plugin-ruby@4.0.4

    - name: Create Prettier config
      run: |
        echo 'printWidth: 100
        tabWidth: 2
        semi: false
        singleQuote: true
        trailingComma: "none"
        plugins:
          - "@prettier/plugin-ruby"
        overrides:
          - files: "**/*.rb"
            options:
              parser: "ruby"' > .prettierrc.yml

    - name: Run Prettier check
      run: npx prettier --check '**/*.rb'

    - name: Install Code Scanning integration
      run: bundle add code-scanning-rubocop --version 0.3.0 --skip-install

    - name: Install dependencies
      run: bundle install

    - name: Rubocop run
      run: |
        bash -c "
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif
          [[ $? -ne 2 ]]
        "

    - name: Upload Sarif output
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: rubocop.sarif
