name: "Rubocop"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '16 5 * * 0'

permissions:
  contents: read
  security-events: write

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.2.1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Prettier and plugin-ruby
        run: npm install prettier @prettier/plugin-ruby

      - name: Create RuboCop config
        run: |
          echo "inherit_from:
            - node_modules/@prettier/plugin-ruby/rubocop.yml
            
          AllCops:
            NewCops: enable
            TargetRubyVersion: 3.2" > .rubocop.yml

      - name: Install Code Scanning integration
        run: bundle add code-scanning-rubocop --version 0.3.0 --skip-install

      - name: Install dependencies
        run: bundle install

      - name: Run RuboCop
        run: |
          bash -c "
            bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif --config .rubocop.yml
            [[ $? -ne 2 ]]
          "

      - name: Upload SARIF output
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rubocop.sarif
