name: "Rubocop with Prettier"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '16 5 * * 0'

permissions:
  contents: read
  security-events: write

jobs:
  rubocop:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
        with:
          ruby-version: 3.2.1

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Prettier and plugin-ruby
        run: |
          npm install prettier@3.4.2 @prettier/plugin-ruby@4.0.4

      - name: Create RuboCop config
        run: |
          echo "# Configuration for RuboCop with Prettier
          inherit_from:
            - node_modules/@prettier/plugin-ruby/rubocop.yml

          AllCops:
            NewCops: enable
            TargetRubyVersion: 3.2
            SuggestExtensions: false
            Exclude:
              - 'node_modules/**/*'
              - 'vendor/**/*'
              - 'bin/**/*'
              - 'db/**/*'
              - 'tmp/**/*'
              - 'config/**/*'" > .rubocop.yml

      - name: Install dependencies
        run: |
          if ! grep -q "code-scanning-rubocop" Gemfile; then
            sed -i '/group :development do/a\  gem "code-scanning-rubocop", "0.3.0", require: false' Gemfile
          fi
          bundle install

      - name: Run Prettier check
        run: npx prettier --check '**/*.rb'

      - name: Run RuboCop
        run: |
          bundle exec rubocop --require code_scanning --format CodeScanning::SarifFormatter -o rubocop.sarif --config .rubocop.yml
          ls -la rubocop.sarif

      - name: Upload SARIF output
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: rubocop.sarif
          wait-for-processing: true
